### ISSUE TITLE
Errno 111 Connection refused

### ISSUE THREAD

**Issue by p4co86** [ubaransel/lgcommander#11] opened 2015-10-22 19:22 UTC
i always get the following error: could someone please help?

its an lg lw5500 tv
```
root@raspberrypi:~/programme/LG# python3 lgcommander.py -H 192.168.0.100 -p 8080 -k DDGURF -c 25
# DEBUG: Detecting accepted protocol.
# DEBUG: Trying to connect to port 3000/tcp
# DEBUG: Testing protocol: hdcp
[Errno 111] Connection refused
```

**Comment by ypid** [comment] 2015-10-22 19:32
First of all, it seems that you are using my [fork of lgcommander](https://github.com/ypid/lgcommander/blob/master/lgcommander.py) because the one from @ubaransel does not have command line switches.

I am not sure what the problem is here. You can try adding `--protocol roap` but I am not sure if that will help.

**Comment by p4co86** [comment] 2015-10-22 19:35
now it works, dont know why but it works with the same command

**Comment by p4co86** [comment] 2015-10-22 19:35
whats the diffenerence between your fork and that one from ubaransel

**Comment by ypid** [comment] 2015-10-22 19:37
See #4. Seems you can close the issue. Maybe your TV was a bit picky.

**Comment by p4co86** [comment] 2015-10-22 19:39
thecommand looks succesful but the volume does not increase

**Comment by ypid** [comment] 2015-10-22 19:40
Try other commands …

**Comment by p4co86** [comment] 2015-10-22 19:44
what does it mean with port 3000 just port 8080 is opened on the tv

**Comment by ypid** [comment] 2015-10-22 19:54
`nmap 192.168.0.100 --reason -vvv -Pn -p 3000,8080` ? It is open … How did you test?

**Comment by p4co86** [comment] 2015-10-22 20:03
i do a nmap 192.168.0.100 and 8080 is the only port that is open it says.

**Comment by p4co86** [comment] 2015-10-22 20:05
with your command it says 

```

PORT     STATE  SERVICE    REASON
3000/tcp closed ppp        reset
8080/tcp open   http-proxy syn-ack

```

**Comment by ypid** [comment] 2015-10-22 20:12
Does not really make sense to me. Both [this script](https://github.com/ypid/lgcommander/blob/3522869bb86e3786d0dd51defd051880efa901b7/lgcommander.py#L205-L232) and nmap check with TCP syn. Looks kind of like there is a advanced packet filter in place somewhere. If you want to debug it, fire up wireshark :wink:.

**Comment by p4co86** [comment] 2015-10-22 20:16
ok what should i do with wireshark? wich settings and what should i post, i dont know how to use it.
thanks for your fast answer !!!!

**Comment by ypid** [comment] 2015-10-22 20:19
I meant if you really want to debug it. The script seems to work as indented but nmap shows something which I and you did not expect … Correct?

You can check the TCP and IP header options and see if there is any difference. Then isolate the packets and try tcpreplay. Just if you like :smile:

**Comment by p4co86** [comment] 2015-10-22 20:21
i try it tomorrow. thanks

**Closed** 2015-11-01 12:09 UTC
